# Generated by Django 4.2.5 on 2024-03-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogPost',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
