# Generated by Django 4.2.5 on 2024-03-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0003_remove_comment_blogpost_remove_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
